# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encoding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'encoding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ncoding.proto\x12\x08\x65ncoding\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\rQueryResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\x1f\n\rImagesRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\">\n\x0eImagesResponse\x12,\n\nembeddings\x18\x01 \x03(\x0b\x32\x18.encoding.ImageEmbedding\"#\n\x0eImageEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\x93\x01\n\x0f\x45ncodingService\x12=\n\nEncodeText\x12\x16.encoding.QueryRequest\x1a\x17.encoding.QueryResponse\x12\x41\n\x0c\x45ncodeImages\x12\x17.encoding.ImagesRequest\x1a\x18.encoding.ImagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encoding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=28
  _globals['_QUERYREQUEST']._serialized_end=57
  _globals['_QUERYRESPONSE']._serialized_start=59
  _globals['_QUERYRESPONSE']._serialized_end=93
  _globals['_IMAGESREQUEST']._serialized_start=95
  _globals['_IMAGESREQUEST']._serialized_end=126
  _globals['_IMAGESRESPONSE']._serialized_start=128
  _globals['_IMAGESRESPONSE']._serialized_end=190
  _globals['_IMAGEEMBEDDING']._serialized_start=192
  _globals['_IMAGEEMBEDDING']._serialized_end=227
  _globals['_ENCODINGSERVICE']._serialized_start=230
  _globals['_ENCODINGSERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
